---
version: '2'
services:
  build:
    build: .
    image: "attilabogar/avb-aur-builder:latest"
    environment:
      - UID=${MYUID}
      - GID=${MYGID}
      - PKGNAME=${PKGNAME}
    volumes:
      - ./workspace:/data/workspace
      - ./repo:/data/repo
      - ./build-helper.sh:/build-helper.sh:ro
